apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliwebapp
  labels:
    app: deliwebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deliwebapp
  template:
    metadata:
      labels:
        app: deliwebapp
  spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
  containers:
      - name: deliwebapp
        image: victork01/deliwebapp:latest
        ports:
        - containerPort: 8080
  imagePullSecrets:
        - name: regcred